name: Format Go
on: [push, pull_request]

jobs:
  run-fmt:
    name: Run fmt
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Gp
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Symlink source into GOPATH for lokify
        run: |
          mkdir -p $(go env GOPATH)/src/github/flared
          ln -s $(pwd) $(go env GOPATH)/src/github/flared/lokify
      
      - name: Run fmt
        run:  go fmt ./...
