name: tests
on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        go-version: [1.x, 1.15.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - run: make go-tests
